// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCShjul8mD862iSeaLo3K5_EdWwl5MlTdc',
    appId: '1:470368958053:web:e23d53f91f200b29a2788c',
    messagingSenderId: '470368958053',
    projectId: 'fit-memoirrrrr',
    authDomain: 'fit-memoirrrrr.firebaseapp.com',
    storageBucket: 'fit-memoirrrrr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeYJbz7KcqYwdb2dzTEcLWTPeI73bosjs',
    appId: '1:470368958053:android:cedfcaf7af1f2540a2788c',
    messagingSenderId: '470368958053',
    projectId: 'fit-memoirrrrr',
    storageBucket: 'fit-memoirrrrr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJshO2dGWmg3Kr-0LWVpVYLlXzWmgd2mc',
    appId: '1:470368958053:ios:ea871da5f7ef0a77a2788c',
    messagingSenderId: '470368958053',
    projectId: 'fit-memoirrrrr',
    storageBucket: 'fit-memoirrrrr.appspot.com',
    iosClientId: '470368958053-8qtc3mgsoaartljnjb4a16biqv19nl7i.apps.googleusercontent.com',
    iosBundleId: 'com.example.meditationApp',
  );
}
